use_frameworks!

platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'WZcommon_Example' do
  pod 'WZcommon', :path => '../'

  target 'WZcommon_Tests' do
    inherit! :search_paths

    
  end
end
